export const LOGIN = "/login"
export const REGISTER = "/registration"
export const SUGGESTION = "/suggestions"
export const DISCOVER = "/suggestions"
export const PROPERTY_DETAILS = "/propertydetails"